//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RielAp.Advertising.TurboSMSService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://turbosms.in.ua/api/Turbo", ItemName="ResultArray")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://turbosms.in.ua/api/Turbo", ConfigurationName="TurboSMSService.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name login from namespace http://turbosms.in.ua/api/Turbo is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://turbosms.in.ua/api/Turbo/Auth", ReplyAction="*")]
        RielAp.Advertising.TurboSMSService.AuthResponse Auth(RielAp.Advertising.TurboSMSService.AuthRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turbosms.in.ua/api/Turbo/Auth", ReplyAction="*")]
        System.Threading.Tasks.Task<RielAp.Advertising.TurboSMSService.AuthResponse> AuthAsync(RielAp.Advertising.TurboSMSService.AuthRequest request);
        
        // CODEGEN: Generating message contract since element name GetCreditBalanceResult from namespace http://turbosms.in.ua/api/Turbo is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://turbosms.in.ua/api/Turbo/GetCreditBalance", ReplyAction="*")]
        RielAp.Advertising.TurboSMSService.GetCreditBalanceResponse GetCreditBalance(RielAp.Advertising.TurboSMSService.GetCreditBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turbosms.in.ua/api/Turbo/GetCreditBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<RielAp.Advertising.TurboSMSService.GetCreditBalanceResponse> GetCreditBalanceAsync(RielAp.Advertising.TurboSMSService.GetCreditBalanceRequest request);
        
        // CODEGEN: Generating message contract since element name sender from namespace http://turbosms.in.ua/api/Turbo is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://turbosms.in.ua/api/Turbo/SendSMS", ReplyAction="*")]
        RielAp.Advertising.TurboSMSService.SendSMSResponse SendSMS(RielAp.Advertising.TurboSMSService.SendSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turbosms.in.ua/api/Turbo/SendSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<RielAp.Advertising.TurboSMSService.SendSMSResponse> SendSMSAsync(RielAp.Advertising.TurboSMSService.SendSMSRequest request);
        
        // CODEGEN: Generating message contract since element name GetNewMessagesResult from namespace http://turbosms.in.ua/api/Turbo is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://turbosms.in.ua/api/Turbo/GetNewMessages", ReplyAction="*")]
        RielAp.Advertising.TurboSMSService.GetNewMessagesResponse GetNewMessages(RielAp.Advertising.TurboSMSService.GetNewMessagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turbosms.in.ua/api/Turbo/GetNewMessages", ReplyAction="*")]
        System.Threading.Tasks.Task<RielAp.Advertising.TurboSMSService.GetNewMessagesResponse> GetNewMessagesAsync(RielAp.Advertising.TurboSMSService.GetNewMessagesRequest request);
        
        // CODEGEN: Generating message contract since element name MessageId from namespace http://turbosms.in.ua/api/Turbo is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://turbosms.in.ua/api/Turbo/GetMessageStatus", ReplyAction="*")]
        RielAp.Advertising.TurboSMSService.GetMessageStatusResponse GetMessageStatus(RielAp.Advertising.TurboSMSService.GetMessageStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://turbosms.in.ua/api/Turbo/GetMessageStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<RielAp.Advertising.TurboSMSService.GetMessageStatusResponse> GetMessageStatusAsync(RielAp.Advertising.TurboSMSService.GetMessageStatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Auth", Namespace="http://turbosms.in.ua/api/Turbo", Order=0)]
        public RielAp.Advertising.TurboSMSService.AuthRequestBody Body;
        
        public AuthRequest() {
        }
        
        public AuthRequest(RielAp.Advertising.TurboSMSService.AuthRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://turbosms.in.ua/api/Turbo")]
    public partial class AuthRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public AuthRequestBody() {
        }
        
        public AuthRequestBody(string login, string password) {
            this.login = login;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthResponse", Namespace="http://turbosms.in.ua/api/Turbo", Order=0)]
        public RielAp.Advertising.TurboSMSService.AuthResponseBody Body;
        
        public AuthResponse() {
        }
        
        public AuthResponse(RielAp.Advertising.TurboSMSService.AuthResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://turbosms.in.ua/api/Turbo")]
    public partial class AuthResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthResult;
        
        public AuthResponseBody() {
        }
        
        public AuthResponseBody(string AuthResult) {
            this.AuthResult = AuthResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCreditBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCreditBalance", Namespace="http://turbosms.in.ua/api/Turbo", Order=0)]
        public RielAp.Advertising.TurboSMSService.GetCreditBalanceRequestBody Body;
        
        public GetCreditBalanceRequest() {
        }
        
        public GetCreditBalanceRequest(RielAp.Advertising.TurboSMSService.GetCreditBalanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCreditBalanceRequestBody {
        
        public GetCreditBalanceRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCreditBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCreditBalanceResponse", Namespace="http://turbosms.in.ua/api/Turbo", Order=0)]
        public RielAp.Advertising.TurboSMSService.GetCreditBalanceResponseBody Body;
        
        public GetCreditBalanceResponse() {
        }
        
        public GetCreditBalanceResponse(RielAp.Advertising.TurboSMSService.GetCreditBalanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://turbosms.in.ua/api/Turbo")]
    public partial class GetCreditBalanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCreditBalanceResult;
        
        public GetCreditBalanceResponseBody() {
        }
        
        public GetCreditBalanceResponseBody(string GetCreditBalanceResult) {
            this.GetCreditBalanceResult = GetCreditBalanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMS", Namespace="http://turbosms.in.ua/api/Turbo", Order=0)]
        public RielAp.Advertising.TurboSMSService.SendSMSRequestBody Body;
        
        public SendSMSRequest() {
        }
        
        public SendSMSRequest(RielAp.Advertising.TurboSMSService.SendSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://turbosms.in.ua/api/Turbo")]
    public partial class SendSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sender;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string destination;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string text;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string wappush;
        
        public SendSMSRequestBody() {
        }
        
        public SendSMSRequestBody(string sender, string destination, string text, string wappush) {
            this.sender = sender;
            this.destination = destination;
            this.text = text;
            this.wappush = wappush;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSResponse", Namespace="http://turbosms.in.ua/api/Turbo", Order=0)]
        public RielAp.Advertising.TurboSMSService.SendSMSResponseBody Body;
        
        public SendSMSResponse() {
        }
        
        public SendSMSResponse(RielAp.Advertising.TurboSMSService.SendSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://turbosms.in.ua/api/Turbo")]
    public partial class SendSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RielAp.Advertising.TurboSMSService.ArrayOfString SendSMSResult;
        
        public SendSMSResponseBody() {
        }
        
        public SendSMSResponseBody(RielAp.Advertising.TurboSMSService.ArrayOfString SendSMSResult) {
            this.SendSMSResult = SendSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewMessagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewMessages", Namespace="http://turbosms.in.ua/api/Turbo", Order=0)]
        public RielAp.Advertising.TurboSMSService.GetNewMessagesRequestBody Body;
        
        public GetNewMessagesRequest() {
        }
        
        public GetNewMessagesRequest(RielAp.Advertising.TurboSMSService.GetNewMessagesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetNewMessagesRequestBody {
        
        public GetNewMessagesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewMessagesResponse", Namespace="http://turbosms.in.ua/api/Turbo", Order=0)]
        public RielAp.Advertising.TurboSMSService.GetNewMessagesResponseBody Body;
        
        public GetNewMessagesResponse() {
        }
        
        public GetNewMessagesResponse(RielAp.Advertising.TurboSMSService.GetNewMessagesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://turbosms.in.ua/api/Turbo")]
    public partial class GetNewMessagesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RielAp.Advertising.TurboSMSService.ArrayOfString GetNewMessagesResult;
        
        public GetNewMessagesResponseBody() {
        }
        
        public GetNewMessagesResponseBody(RielAp.Advertising.TurboSMSService.ArrayOfString GetNewMessagesResult) {
            this.GetNewMessagesResult = GetNewMessagesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessageStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessageStatus", Namespace="http://turbosms.in.ua/api/Turbo", Order=0)]
        public RielAp.Advertising.TurboSMSService.GetMessageStatusRequestBody Body;
        
        public GetMessageStatusRequest() {
        }
        
        public GetMessageStatusRequest(RielAp.Advertising.TurboSMSService.GetMessageStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://turbosms.in.ua/api/Turbo")]
    public partial class GetMessageStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MessageId;
        
        public GetMessageStatusRequestBody() {
        }
        
        public GetMessageStatusRequestBody(string MessageId) {
            this.MessageId = MessageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessageStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessageStatusResponse", Namespace="http://turbosms.in.ua/api/Turbo", Order=0)]
        public RielAp.Advertising.TurboSMSService.GetMessageStatusResponseBody Body;
        
        public GetMessageStatusResponse() {
        }
        
        public GetMessageStatusResponse(RielAp.Advertising.TurboSMSService.GetMessageStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://turbosms.in.ua/api/Turbo")]
    public partial class GetMessageStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetMessageStatusResult;
        
        public GetMessageStatusResponseBody() {
        }
        
        public GetMessageStatusResponseBody(string GetMessageStatusResult) {
            this.GetMessageStatusResult = GetMessageStatusResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : RielAp.Advertising.TurboSMSService.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<RielAp.Advertising.TurboSMSService.ServiceSoap>, RielAp.Advertising.TurboSMSService.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RielAp.Advertising.TurboSMSService.AuthResponse RielAp.Advertising.TurboSMSService.ServiceSoap.Auth(RielAp.Advertising.TurboSMSService.AuthRequest request) {
            return base.Channel.Auth(request);
        }
        
        public string Auth(string login, string password) {
            RielAp.Advertising.TurboSMSService.AuthRequest inValue = new RielAp.Advertising.TurboSMSService.AuthRequest();
            inValue.Body = new RielAp.Advertising.TurboSMSService.AuthRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            RielAp.Advertising.TurboSMSService.AuthResponse retVal = ((RielAp.Advertising.TurboSMSService.ServiceSoap)(this)).Auth(inValue);
            return retVal.Body.AuthResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RielAp.Advertising.TurboSMSService.AuthResponse> RielAp.Advertising.TurboSMSService.ServiceSoap.AuthAsync(RielAp.Advertising.TurboSMSService.AuthRequest request) {
            return base.Channel.AuthAsync(request);
        }
        
        public System.Threading.Tasks.Task<RielAp.Advertising.TurboSMSService.AuthResponse> AuthAsync(string login, string password) {
            RielAp.Advertising.TurboSMSService.AuthRequest inValue = new RielAp.Advertising.TurboSMSService.AuthRequest();
            inValue.Body = new RielAp.Advertising.TurboSMSService.AuthRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            return ((RielAp.Advertising.TurboSMSService.ServiceSoap)(this)).AuthAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RielAp.Advertising.TurboSMSService.GetCreditBalanceResponse RielAp.Advertising.TurboSMSService.ServiceSoap.GetCreditBalance(RielAp.Advertising.TurboSMSService.GetCreditBalanceRequest request) {
            return base.Channel.GetCreditBalance(request);
        }
        
        public string GetCreditBalance() {
            RielAp.Advertising.TurboSMSService.GetCreditBalanceRequest inValue = new RielAp.Advertising.TurboSMSService.GetCreditBalanceRequest();
            inValue.Body = new RielAp.Advertising.TurboSMSService.GetCreditBalanceRequestBody();
            RielAp.Advertising.TurboSMSService.GetCreditBalanceResponse retVal = ((RielAp.Advertising.TurboSMSService.ServiceSoap)(this)).GetCreditBalance(inValue);
            return retVal.Body.GetCreditBalanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RielAp.Advertising.TurboSMSService.GetCreditBalanceResponse> RielAp.Advertising.TurboSMSService.ServiceSoap.GetCreditBalanceAsync(RielAp.Advertising.TurboSMSService.GetCreditBalanceRequest request) {
            return base.Channel.GetCreditBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<RielAp.Advertising.TurboSMSService.GetCreditBalanceResponse> GetCreditBalanceAsync() {
            RielAp.Advertising.TurboSMSService.GetCreditBalanceRequest inValue = new RielAp.Advertising.TurboSMSService.GetCreditBalanceRequest();
            inValue.Body = new RielAp.Advertising.TurboSMSService.GetCreditBalanceRequestBody();
            return ((RielAp.Advertising.TurboSMSService.ServiceSoap)(this)).GetCreditBalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RielAp.Advertising.TurboSMSService.SendSMSResponse RielAp.Advertising.TurboSMSService.ServiceSoap.SendSMS(RielAp.Advertising.TurboSMSService.SendSMSRequest request) {
            return base.Channel.SendSMS(request);
        }
        
        public RielAp.Advertising.TurboSMSService.ArrayOfString SendSMS(string sender, string destination, string text, string wappush) {
            RielAp.Advertising.TurboSMSService.SendSMSRequest inValue = new RielAp.Advertising.TurboSMSService.SendSMSRequest();
            inValue.Body = new RielAp.Advertising.TurboSMSService.SendSMSRequestBody();
            inValue.Body.sender = sender;
            inValue.Body.destination = destination;
            inValue.Body.text = text;
            inValue.Body.wappush = wappush;
            RielAp.Advertising.TurboSMSService.SendSMSResponse retVal = ((RielAp.Advertising.TurboSMSService.ServiceSoap)(this)).SendSMS(inValue);
            return retVal.Body.SendSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RielAp.Advertising.TurboSMSService.SendSMSResponse> RielAp.Advertising.TurboSMSService.ServiceSoap.SendSMSAsync(RielAp.Advertising.TurboSMSService.SendSMSRequest request) {
            return base.Channel.SendSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<RielAp.Advertising.TurboSMSService.SendSMSResponse> SendSMSAsync(string sender, string destination, string text, string wappush) {
            RielAp.Advertising.TurboSMSService.SendSMSRequest inValue = new RielAp.Advertising.TurboSMSService.SendSMSRequest();
            inValue.Body = new RielAp.Advertising.TurboSMSService.SendSMSRequestBody();
            inValue.Body.sender = sender;
            inValue.Body.destination = destination;
            inValue.Body.text = text;
            inValue.Body.wappush = wappush;
            return ((RielAp.Advertising.TurboSMSService.ServiceSoap)(this)).SendSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RielAp.Advertising.TurboSMSService.GetNewMessagesResponse RielAp.Advertising.TurboSMSService.ServiceSoap.GetNewMessages(RielAp.Advertising.TurboSMSService.GetNewMessagesRequest request) {
            return base.Channel.GetNewMessages(request);
        }
        
        public RielAp.Advertising.TurboSMSService.ArrayOfString GetNewMessages() {
            RielAp.Advertising.TurboSMSService.GetNewMessagesRequest inValue = new RielAp.Advertising.TurboSMSService.GetNewMessagesRequest();
            inValue.Body = new RielAp.Advertising.TurboSMSService.GetNewMessagesRequestBody();
            RielAp.Advertising.TurboSMSService.GetNewMessagesResponse retVal = ((RielAp.Advertising.TurboSMSService.ServiceSoap)(this)).GetNewMessages(inValue);
            return retVal.Body.GetNewMessagesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RielAp.Advertising.TurboSMSService.GetNewMessagesResponse> RielAp.Advertising.TurboSMSService.ServiceSoap.GetNewMessagesAsync(RielAp.Advertising.TurboSMSService.GetNewMessagesRequest request) {
            return base.Channel.GetNewMessagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<RielAp.Advertising.TurboSMSService.GetNewMessagesResponse> GetNewMessagesAsync() {
            RielAp.Advertising.TurboSMSService.GetNewMessagesRequest inValue = new RielAp.Advertising.TurboSMSService.GetNewMessagesRequest();
            inValue.Body = new RielAp.Advertising.TurboSMSService.GetNewMessagesRequestBody();
            return ((RielAp.Advertising.TurboSMSService.ServiceSoap)(this)).GetNewMessagesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RielAp.Advertising.TurboSMSService.GetMessageStatusResponse RielAp.Advertising.TurboSMSService.ServiceSoap.GetMessageStatus(RielAp.Advertising.TurboSMSService.GetMessageStatusRequest request) {
            return base.Channel.GetMessageStatus(request);
        }
        
        public string GetMessageStatus(string MessageId) {
            RielAp.Advertising.TurboSMSService.GetMessageStatusRequest inValue = new RielAp.Advertising.TurboSMSService.GetMessageStatusRequest();
            inValue.Body = new RielAp.Advertising.TurboSMSService.GetMessageStatusRequestBody();
            inValue.Body.MessageId = MessageId;
            RielAp.Advertising.TurboSMSService.GetMessageStatusResponse retVal = ((RielAp.Advertising.TurboSMSService.ServiceSoap)(this)).GetMessageStatus(inValue);
            return retVal.Body.GetMessageStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RielAp.Advertising.TurboSMSService.GetMessageStatusResponse> RielAp.Advertising.TurboSMSService.ServiceSoap.GetMessageStatusAsync(RielAp.Advertising.TurboSMSService.GetMessageStatusRequest request) {
            return base.Channel.GetMessageStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<RielAp.Advertising.TurboSMSService.GetMessageStatusResponse> GetMessageStatusAsync(string MessageId) {
            RielAp.Advertising.TurboSMSService.GetMessageStatusRequest inValue = new RielAp.Advertising.TurboSMSService.GetMessageStatusRequest();
            inValue.Body = new RielAp.Advertising.TurboSMSService.GetMessageStatusRequestBody();
            inValue.Body.MessageId = MessageId;
            return ((RielAp.Advertising.TurboSMSService.ServiceSoap)(this)).GetMessageStatusAsync(inValue);
        }
    }
}
