// <auto-generated />
namespace RielAp.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addTypeToLand : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTypeToLand));
        
        string IMigrationMetadata.Id
        {
            get { return "201309031202333_addTypeToLand"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
