// <auto-generated />
namespace RielAp.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addRole : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addRole));
        
        string IMigrationMetadata.Id
        {
            get { return "201309181137117_addRole"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
