// <auto-generated />
namespace RielAp.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addUserConfirmation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addUserConfirmation));
        
        string IMigrationMetadata.Id
        {
            get { return "201309041243361_addUserConfirmation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
