// <auto-generated />
namespace RielAp.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addStatistic : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addStatistic));
        
        string IMigrationMetadata.Id
        {
            get { return "201402061618329_addStatistic"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
