//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RielAp.Translation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RielAp.Translation.Translation", typeof(Translation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Якщо Вам набридло платити за розміщення оголошень з нерухомості, слідкувати чи ваше оголошення є на сайті, подавати кожен раз оголошення після того як воно зникло, тоді Вам потрібно зареєструватися на цьому сайті і керувати своїми оголошеннями самостійно. Цей сайт надає можливість &lt;strong&gt;безкоштовного пошуку оголошень&lt;/strong&gt; про продаж і оренду нерухомості, а також &lt;strong&gt;подачі до {0} безкоштовних оголошень з фотографіями&lt;/strong&gt;. Для подачі оголошень Вам потрібно &lt;a href=&quot;{1}&quot;&gt;зареєструватися&lt;/a&gt;. Дл [rest of string was truncated]&quot;;.
        /// </summary>
        public static string a {
            get {
                return ResourceManager.GetString("a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вам відмовлено в доступі.
        /// </summary>
        public static string AccessIsDeniedMessage {
            get {
                return ResourceManager.GetString("AccessIsDeniedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагування профілю.
        /// </summary>
        public static string AccountProfileEditTitle {
            get {
                return ResourceManager.GetString("AccountProfileEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тарифний план.
        /// </summary>
        public static string AccountUpdateLimitTitle {
            get {
                return ResourceManager.GetString("AccountUpdateLimitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подати оголошення.
        /// </summary>
        public static string AddAnnouncement {
            get {
                return ResourceManager.GetString("AddAnnouncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати фотографію.
        /// </summary>
        public static string AddPhotoBtnLabel {
            get {
                return ResourceManager.GetString("AddPhotoBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Місто.
        /// </summary>
        public static string AddressTypeCityLabel {
            get {
                return ResourceManager.GetString("AddressTypeCityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невідомо.
        /// </summary>
        public static string AddressTypeUnknownLabel {
            get {
                return ResourceManager.GetString("AddressTypeUnknownLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Область.
        /// </summary>
        public static string AddressTypeVillargeLabel {
            get {
                return ResourceManager.GetString("AddressTypeVillargeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Область.
        /// </summary>
        public static string AnnouncementAddressAdministrativeAreaLabel {
            get {
                return ResourceManager.GetString("AnnouncementAddressAdministrativeAreaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Район.
        /// </summary>
        public static string AnnouncementAddressDistrictLabel {
            get {
                return ResourceManager.GetString("AnnouncementAddressDistrictLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Населений пункт.
        /// </summary>
        public static string AnnouncementAddressLocalityNameLabel {
            get {
                return ResourceManager.GetString("AnnouncementAddressLocalityNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вулиця.
        /// </summary>
        public static string AnnouncementAddressStreetLabel {
            get {
                return ResourceManager.GetString("AnnouncementAddressStreetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Район.
        /// </summary>
        public static string AnnouncementAddressSubAdministrativeAreaLabel {
            get {
                return ResourceManager.GetString("AnnouncementAddressSubAdministrativeAreaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип адреси.
        /// </summary>
        public static string AnnouncementAddressTypeLabel {
            get {
                return ResourceManager.GetString("AnnouncementAddressTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер будинку.
        /// </summary>
        public static string AnnouncementBuildingNumber {
            get {
                return ResourceManager.GetString("AnnouncementBuildingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Місто.
        /// </summary>
        public static string AnnouncementCityLabel {
            get {
                return ResourceManager.GetString("AnnouncementCityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Район.
        /// </summary>
        public static string AnnouncementDistrictLabel {
            get {
                return ResourceManager.GetString("AnnouncementDistrictLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адреса.
        /// </summary>
        public static string AnnouncementEditAddress {
            get {
                return ResourceManager.GetString("AnnouncementEditAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ввести адресу самому.
        /// </summary>
        public static string AnnouncementEditAddressInputType {
            get {
                return ResourceManager.GetString("AnnouncementEditAddressInputType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Житлова площа.
        /// </summary>
        public static string AnnouncementEditApartmentLivingSquareLabel {
            get {
                return ResourceManager.GetString("AnnouncementEditApartmentLivingSquareLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загальна площа.
        /// </summary>
        public static string AnnouncementEditApartmentTotalSquareLabel {
            get {
                return ResourceManager.GetString("AnnouncementEditApartmentTotalSquareLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відмінити.
        /// </summary>
        public static string AnnouncementEditBackButtonLabel {
            get {
                return ResourceManager.GetString("AnnouncementEditBackButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клацніть мишкою по карті, щоб вибрати адресу автоматично(рекомендовано). Або виберіть &quot;Ввести адресу самому&quot; і введіть адресу самому. Правильність введеної адреси ви можете перевірити клацнувши по кнопці &quot;Показати на карті&quot;..
        /// </summary>
        public static string AnnouncementEditHintSetAddressLabel {
            get {
                return ResourceManager.GetString("AnnouncementEditHintSetAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інформація.
        /// </summary>
        public static string AnnouncementEditInfos {
            get {
                return ResourceManager.GetString("AnnouncementEditInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Призначення.
        /// </summary>
        public static string AnnouncementEditLandApplyTypeLabel {
            get {
                return ResourceManager.GetString("AnnouncementEditLandApplyTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фотографії.
        /// </summary>
        public static string AnnouncementEditPhotos {
            get {
                return ResourceManager.GetString("AnnouncementEditPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберегти.
        /// </summary>
        public static string AnnouncementEditSaveButtonLabel {
            get {
                return ResourceManager.GetString("AnnouncementEditSaveButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За адресою (від Я до А).
        /// </summary>
        public static string AnnouncementOrderAddressDescendingLabel {
            get {
                return ResourceManager.GetString("AnnouncementOrderAddressDescendingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За адресою (від А до Я).
        /// </summary>
        public static string AnnouncementOrderAddressLabel {
            get {
                return ResourceManager.GetString("AnnouncementOrderAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За датою(спершу старші).
        /// </summary>
        public static string AnnouncementOrderDateDescendingLabel {
            get {
                return ResourceManager.GetString("AnnouncementOrderDateDescendingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За датою(спершу новіші).
        /// </summary>
        public static string AnnouncementOrderDateLabel {
            get {
                return ResourceManager.GetString("AnnouncementOrderDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сортувати.
        /// </summary>
        public static string AnnouncementOrderLabel {
            get {
                return ResourceManager.GetString("AnnouncementOrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показувати номер будинку.
        /// </summary>
        public static string AnnouncementShowBuildingNumber {
            get {
                return ResourceManager.GetString("AnnouncementShowBuildingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вулиця.
        /// </summary>
        public static string AnnouncementStreetLabel {
            get {
                return ResourceManager.GetString("AnnouncementStreetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип оголошення.
        /// </summary>
        public static string AnnouncementType {
            get {
                return ResourceManager.GetString("AnnouncementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип.
        /// </summary>
        public static string AnnouncementTypeLabel {
            get {
                return ResourceManager.GetString("AnnouncementTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид.
        /// </summary>
        public static string AnnouncementViewLabel {
            get {
                return ResourceManager.GetString("AnnouncementViewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квартира.
        /// </summary>
        public static string ApartmentAnnouncementLabel {
            get {
                return ResourceManager.GetString("ApartmentAnnouncementLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наявність балкону.
        /// </summary>
        public static string ApartmentDetailsPageBalconyLabel {
            get {
                return ResourceManager.GetString("ApartmentDetailsPageBalconyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата створення оголошення.
        /// </summary>
        public static string ApartmentDetailsPageCreationDateLabel {
            get {
                return ResourceManager.GetString("ApartmentDetailsPageCreationDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Днів на сайті.
        /// </summary>
        public static string ApartmentDetailsPageDaysOnSiteLabel {
            get {
                return ResourceManager.GetString("ApartmentDetailsPageDaysOnSiteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вхід з.
        /// </summary>
        public static string ApartmentDetailsPageEntranceFromLabel {
            get {
                return ResourceManager.GetString("ApartmentDetailsPageEntranceFromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вхід у.
        /// </summary>
        public static string ApartmentDetailsPageEntranceInLabel {
            get {
                return ResourceManager.GetString("ApartmentDetailsPageEntranceInLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поверх.
        /// </summary>
        public static string ApartmentDetailsPageFloorLabel {
            get {
                return ResourceManager.GetString("ApartmentDetailsPageFloorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перекриття.
        /// </summary>
        public static string ApartmentDetailsPageFloorMaterialsLabel {
            get {
                return ResourceManager.GetString("ApartmentDetailsPageFloorMaterialsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип опалення.
        /// </summary>
        public static string ApartmentDetailsPageHeatingTypeLabel {
            get {
                return ResourceManager.GetString("ApartmentDetailsPageHeatingTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип постачання гарячої води.
        /// </summary>
        public static string ApartmentDetailsPageHotWaterTypeLabel {
            get {
                return ResourceManager.GetString("ApartmentDetailsPageHotWaterTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Примітка.
        /// </summary>
        public static string ApartmentDetailsPageNoticeLabel {
            get {
                return ResourceManager.GetString("ApartmentDetailsPageNoticeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фотографії.
        /// </summary>
        public static string ApartmentDetailsPagePicturesLabel {
            get {
                return ResourceManager.GetString("ApartmentDetailsPagePicturesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Місце під авто.
        /// </summary>
        public static string ApartmentDetailsPagePlaceForCarLabel {
            get {
                return ResourceManager.GetString("ApartmentDetailsPagePlaceForCarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ціна.
        /// </summary>
        public static string ApartmentDetailsPagePriceLabel {
            get {
                return ResourceManager.GetString("ApartmentDetailsPagePriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кількість кімнат.
        /// </summary>
        public static string ApartmentDetailsPageRoomsCountLabel {
            get {
                return ResourceManager.GetString("ApartmentDetailsPageRoomsCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Площа.
        /// </summary>
        public static string ApartmentDetailsPageSquareLabel {
            get {
                return ResourceManager.GetString("ApartmentDetailsPageSquareLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деталі.
        /// </summary>
        public static string ApartmentDetailsPageTitle {
            get {
                return ResourceManager.GetString("ApartmentDetailsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер телефону продавця.
        /// </summary>
        public static string ApartmentDetailsPageUserPhoneLabel {
            get {
                return ResourceManager.GetString("ApartmentDetailsPageUserPhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стіни.
        /// </summary>
        public static string ApartmentDetailsPageWallMaterialsLabel {
            get {
                return ResourceManager.GetString("ApartmentDetailsPageWallMaterialsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список квартир.
        /// </summary>
        public static string ApartmentsListTitle {
            get {
                return ResourceManager.GetString("ApartmentsListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квартири на карті.
        /// </summary>
        public static string ApartmentsMapTitle {
            get {
                return ResourceManager.GetString("ApartmentsMapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продаж.
        /// </summary>
        public static string BuySellLabel {
            get {
                return ResourceManager.GetString("BuySellLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подати оголошення.
        /// </summary>
        public static string CabinetAddAnnouncement {
            get {
                return ResourceManager.GetString("CabinetAddAnnouncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подати оголошення про квартиру.
        /// </summary>
        public static string CabinetAddApartmentLabel {
            get {
                return ResourceManager.GetString("CabinetAddApartmentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати відгук.
        /// </summary>
        public static string CabinetAddFeedbackLabel {
            get {
                return ResourceManager.GetString("CabinetAddFeedbackLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подати оголошення про будинок.
        /// </summary>
        public static string CabinetAddHouseLabel {
            get {
                return ResourceManager.GetString("CabinetAddHouseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додатковий номер телефону.
        /// </summary>
        public static string CabinetAdditionalUserNumberLabel {
            get {
                return ResourceManager.GetString("CabinetAdditionalUserNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подати оголошення про ділянку.
        /// </summary>
        public static string CabinetAddLandLabel {
            get {
                return ResourceManager.GetString("CabinetAddLandLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати номер телефону.
        /// </summary>
        public static string CabinetAddUserPhoneLabel {
            get {
                return ResourceManager.GetString("CabinetAddUserPhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви можете додати ще &lt;strong&gt;{0}&lt;/strong&gt; оголошень..
        /// </summary>
        public static string CabinetAnnouncementLeft {
            get {
                return ResourceManager.GetString("CabinetAnnouncementLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оголошення.
        /// </summary>
        public static string CabinetAnnouncementsListTitle {
            get {
                return ResourceManager.GetString("CabinetAnnouncementsListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відмінити.
        /// </summary>
        public static string CabinetCancelUserInfoLabel {
            get {
                return ResourceManager.GetString("CabinetCancelUserInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дані видалено.
        /// </summary>
        public static string CabinetDataDeleteMessage {
            get {
                return ResourceManager.GetString("CabinetDataDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дані збережені.
        /// </summary>
        public static string CabinetDataSavedMessage {
            get {
                return ResourceManager.GetString("CabinetDataSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стерти.
        /// </summary>
        public static string CabinetDeleteAnnouncementLabel {
            get {
                return ResourceManager.GetString("CabinetDeleteAnnouncementLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити.
        /// </summary>
        public static string CabinetDeleteUserPhoneLabel {
            get {
                return ResourceManager.GetString("CabinetDeleteUserPhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деталі.
        /// </summary>
        public static string CabinetDetailsAnnouncementLabel {
            get {
                return ResourceManager.GetString("CabinetDetailsAnnouncementLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагувати.
        /// </summary>
        public static string CabinetEditAnnouncementLabel {
            get {
                return ResourceManager.GetString("CabinetEditAnnouncementLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відгуки.
        /// </summary>
        public static string CabinetFeedbacksListTitle {
            get {
                return ResourceManager.GetString("CabinetFeedbacksListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основний номер телефону.
        /// </summary>
        public static string CabinetMainUserPhoneLabel {
            get {
                return ResourceManager.GetString("CabinetMainUserPhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У даного кориcтувача відсутні оголошення.
        /// </summary>
        public static string CabinetNoAnnouncementsInUser {
            get {
                return ResourceManager.GetString("CabinetNoAnnouncementsInUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У даного кориcтувача відсутні відгуки.
        /// </summary>
        public static string CabinetNoFeedbacksInUser {
            get {
                return ResourceManager.GetString("CabinetNoFeedbacksInUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберегти.
        /// </summary>
        public static string CabinetSaveLabel {
            get {
                return ResourceManager.GetString("CabinetSaveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберегти.
        /// </summary>
        public static string CabinetSaveUserInfoLabel {
            get {
                return ResourceManager.GetString("CabinetSaveUserInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кабінет.
        /// </summary>
        public static string CabinetTitlePage {
            get {
                return ResourceManager.GetString("CabinetTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інформація про користувача.
        /// </summary>
        public static string CabinetUserInfoTitle {
            get {
                return ResourceManager.GetString("CabinetUserInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кількість оголошень.
        /// </summary>
        public static string CabinetUserProfileAnnouncementsCountLabel {
            get {
                return ResourceManager.GetString("CabinetUserProfileAnnouncementsCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагувати.
        /// </summary>
        public static string CabinetUserProfileEditLabel {
            get {
                return ResourceManager.GetString("CabinetUserProfileEditLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номери телефонів.
        /// </summary>
        public static string CabinetUserProfileNumbersLabel {
            get {
                return ResourceManager.GetString("CabinetUserProfileNumbersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви зареєструвалися на сайті {0}. Для підтвердження правдивості користувача перейдіть, будь ласка за цим посиланням:&lt;p&gt;&lt;a href=&quot;{1}&quot;&gt;{1}&lt;/a&gt;&lt;/p&gt;. &lt;p&gt;Якщо Ви не реєструвалися на {0}, то проігноруйте цей лист.&lt;/p&gt;.
        /// </summary>
        public static string ConfirmationMailBody {
            get {
                return ResourceManager.GetString("ConfirmationMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підтвердження користувача - сайт нерухомості.
        /// </summary>
        public static string ConfirmationMailTitle {
            get {
                return ResourceManager.GetString("ConfirmationMailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string DollarLabel {
            get {
                return ResourceManager.GetString("DollarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показати на карті.
        /// </summary>
        public static string EditAnnouncementAddressShowOnMapLabel {
            get {
                return ResourceManager.GetString("EditAnnouncementAddressShowOnMapLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагування оголошення про квартиру.
        /// </summary>
        public static string EditApartmentAnnouncementTitle {
            get {
                return ResourceManager.GetString("EditApartmentAnnouncementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квартира.
        /// </summary>
        public static string EditApartmentApartmentTitle {
            get {
                return ResourceManager.GetString("EditApartmentApartmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагування оголошення про будинок.
        /// </summary>
        public static string EditHouseAnnouncementTitle {
            get {
                return ResourceManager.GetString("EditHouseAnnouncementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагування оголошення про ділянку.
        /// </summary>
        public static string EditLandAnnouncementTitle {
            get {
                return ResourceManager.GetString("EditLandAnnouncementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш тарифний план закінчується на сайті aparts.in.ua закінчується через {0} днів. Будь ласка, &lt;a href=&quot;{1}&quot;&gt;продовжіть ваш тарифний план&lt;/a&gt;. Якщо Ви не продовжите його то ви буете переведені на базовий тарифний план і тільки останні 5 оголошень будуть видимі для користувачів. Якщо Ви продовжите свій тарифний план після того як вийде термін його термін дії, тоді ваші старі оголошення знову стануть видимі..
        /// </summary>
        public static string EmailProfileWillBeExpiredBody {
            get {
                return ResourceManager.GetString("EmailProfileWillBeExpiredBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш тарифний план закінчується через {0} днів..
        /// </summary>
        public static string EmailProfileWillBeExpiredTitle {
            get {
                return ResourceManager.GetString("EmailProfileWillBeExpiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to З балкону.
        /// </summary>
        public static string EntranceFromBalconyLabel {
            get {
                return ResourceManager.GetString("EntranceFromBalconyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Парадний(з сходової клітки).
        /// </summary>
        public static string EntranceFromStairCaseLabel {
            get {
                return ResourceManager.GetString("EntranceFromStairCaseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невідомо.
        /// </summary>
        public static string EntranceFromUnknownLabel {
            get {
                return ResourceManager.GetString("EntranceFromUnknownLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to З подвір&apos;я.
        /// </summary>
        public static string EntranceFromYardLabel {
            get {
                return ResourceManager.GetString("EntranceFromYardLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коридор.
        /// </summary>
        public static string EntranceInCorridorLabel {
            get {
                return ResourceManager.GetString("EntranceInCorridorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кухню.
        /// </summary>
        public static string EntranceInKitchenLabel {
            get {
                return ResourceManager.GetString("EntranceInKitchenLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невідомо.
        /// </summary>
        public static string EntranceInUnknownLabel {
            get {
                return ResourceManager.GetString("EntranceInUnknownLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Щось пішло не так!.
        /// </summary>
        public static string ErrorExceptionMessage {
            get {
                return ResourceManager.GetString("ErrorExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Даний ресурс не знайдено!.
        /// </summary>
        public static string ErrorNotFoundMessage {
            get {
                return ResourceManager.GetString("ErrorNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати відгук.
        /// </summary>
        public static string FeedbackAddButtonLabel {
            get {
                return ResourceManager.GetString("FeedbackAddButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати відгук.
        /// </summary>
        public static string FeedbackAddTitle {
            get {
                return ResourceManager.GetString("FeedbackAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Електронна адреса автора.
        /// </summary>
        public static string FeedbackAuthorEmailLabel {
            get {
                return ResourceManager.GetString("FeedbackAuthorEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор.
        /// </summary>
        public static string FeedbackAuthorNameLabel {
            get {
                return ResourceManager.GetString("FeedbackAuthorNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FeedbackBack {
            get {
                return ResourceManager.GetString("FeedbackBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад до відгуків.
        /// </summary>
        public static string FeedbackBackToListButtonLabel {
            get {
                return ResourceManager.GetString("FeedbackBackToListButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст повідомлення.
        /// </summary>
        public static string FeedbackBodyLabel {
            get {
                return ResourceManager.GetString("FeedbackBodyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відгуки.
        /// </summary>
        public static string FeedbackListLabel {
            get {
                return ResourceManager.GetString("FeedbackListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На даний момент відгуків немає.
        /// </summary>
        public static string FeedbackNoFeedbacksYet {
            get {
                return ResourceManager.GetString("FeedbackNoFeedbacksYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок.
        /// </summary>
        public static string FeedbackSubjectLabel {
            get {
                return ResourceManager.GetString("FeedbackSubjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відгуки та зауваження до сайту.
        /// </summary>
        public static string FeedbacksWebsiteTitle {
            get {
                return ResourceManager.GetString("FeedbacksWebsiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невірний формат введених даних.
        /// </summary>
        public static string FilterInputIncorrectLabel {
            get {
                return ResourceManager.GetString("FilterInputIncorrectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дерево.
        /// </summary>
        public static string FloorMaterialDerevoLabel {
            get {
                return ResourceManager.GetString("FloorMaterialDerevoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невідомо.
        /// </summary>
        public static string FloorMaterialUnknownLabel {
            get {
                return ResourceManager.GetString("FloorMaterialUnknownLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to З/б і дерево.
        /// </summary>
        public static string FloorMaterialZalizoBetonIDerevoLabel {
            get {
                return ResourceManager.GetString("FloorMaterialZalizoBetonIDerevoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Залізо-бетон.
        /// </summary>
        public static string FloorMaterialZalizoBetonLabel {
            get {
                return ResourceManager.GetString("FloorMaterialZalizoBetonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забули пароль?.
        /// </summary>
        public static string ForgetPasswordLabel {
            get {
                return ResourceManager.GetString("ForgetPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відправити пароль на електронну пошту.
        /// </summary>
        public static string ForgetPasswordSendButton {
            get {
                return ResourceManager.GetString("ForgetPasswordSendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повідомлення з паролем успішно відправленне.
        /// </summary>
        public static string ForgetPasswordSuccess {
            get {
                return ResourceManager.GetString("ForgetPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відновлення паролю.
        /// </summary>
        public static string ForgetPasswordTitle {
            get {
                return ResourceManager.GetString("ForgetPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загальне.
        /// </summary>
        public static string GeneralProfileManagerTitle {
            get {
                return ResourceManager.GetString("GeneralProfileManagerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Центральне опалення.
        /// </summary>
        public static string HeatingTypeCentralLabel {
            get {
                return ResourceManager.GetString("HeatingTypeCentralLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Котел.
        /// </summary>
        public static string HeatingTypeGasBoilerLabel {
            get {
                return ResourceManager.GetString("HeatingTypeGasBoilerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пічка.
        /// </summary>
        public static string HeatingTypeStoveLabel {
            get {
                return ResourceManager.GetString("HeatingTypeStoveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невідомо.
        /// </summary>
        public static string HeatingTypeUnknownLabel {
            get {
                return ResourceManager.GetString("HeatingTypeUnknownLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привіт,.
        /// </summary>
        public static string HelloMessageLabel {
            get {
                return ResourceManager.GetString("HelloMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підказка!.
        /// </summary>
        public static string HintLabel {
            get {
                return ResourceManager.GetString("HintLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Котел.
        /// </summary>
        public static string HotWaterTypeBoilerLabel {
            get {
                return ResourceManager.GetString("HotWaterTypeBoilerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цетральне.
        /// </summary>
        public static string HotWaterTypeCentralLabel {
            get {
                return ResourceManager.GetString("HotWaterTypeCentralLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Колонка.
        /// </summary>
        public static string HotWaterTypeGeyserLabel {
            get {
                return ResourceManager.GetString("HotWaterTypeGeyserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невідомо.
        /// </summary>
        public static string HotWaterTypeUnknownLabel {
            get {
                return ResourceManager.GetString("HotWaterTypeUnknownLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бойлер.
        /// </summary>
        public static string HotWaterTypeWaterBoilerLabel {
            get {
                return ResourceManager.GetString("HotWaterTypeWaterBoilerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будинок.
        /// </summary>
        public static string HouseAnnouncementLabel {
            get {
                return ResourceManager.GetString("HouseAnnouncementLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деталі будинку.
        /// </summary>
        public static string HouseDetailsPageTitle {
            get {
                return ResourceManager.GetString("HouseDetailsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Площа будинку.
        /// </summary>
        public static string HousesDetailsPageSquareLabel {
            get {
                return ResourceManager.GetString("HousesDetailsPageSquareLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список будинків.
        /// </summary>
        public static string HousesListTitle {
            get {
                return ResourceManager.GetString("HousesListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будинки на карті.
        /// </summary>
        public static string HousesMapTitle {
            get {
                return ResourceManager.GetString("HousesMapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to грн..
        /// </summary>
        public static string HryvnaLabel {
            get {
                return ResourceManager.GetString("HryvnaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будь ласка, проставте адресу правильно.
        /// </summary>
        public static string InvalidAddressMessage {
            get {
                return ResourceManager.GetString("InvalidAddressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невірно введені дані.
        /// </summary>
        public static string InvalidAnnouncementMessage {
            get {
                return ResourceManager.GetString("InvalidAnnouncementMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ділянка.
        /// </summary>
        public static string LandAnnouncementLabel {
            get {
                return ResourceManager.GetString("LandAnnouncementLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Під забудову.
        /// </summary>
        public static string LandApplyTypeForBuildingLabel {
            get {
                return ResourceManager.GetString("LandApplyTypeForBuildingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дача.
        /// </summary>
        public static string LandApplyTypeSummerHouseLabel {
            get {
                return ResourceManager.GetString("LandApplyTypeSummerHouseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невідомо.
        /// </summary>
        public static string LandApplyTypeUnknownLabel {
            get {
                return ResourceManager.GetString("LandApplyTypeUnknownLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деталі квартири.
        /// </summary>
        public static string LandDetailsPageTitle {
            get {
                return ResourceManager.GetString("LandDetailsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Призначення.
        /// </summary>
        public static string LandsDetailsPageApplyTypeLabel {
            get {
                return ResourceManager.GetString("LandsDetailsPageApplyTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Площа ділянки.
        /// </summary>
        public static string LandsDetailsPageSquareLabel {
            get {
                return ResourceManager.GetString("LandsDetailsPageSquareLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список ділянок.
        /// </summary>
        public static string LandsListTitle {
            get {
                return ResourceManager.GetString("LandsListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ділянки на карті.
        /// </summary>
        public static string LandsMapTitle {
            get {
                return ResourceManager.GetString("LandsMapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квартири.
        /// </summary>
        public static string LayoutNavigationApartments {
            get {
                return ResourceManager.GetString("LayoutNavigationApartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будинки.
        /// </summary>
        public static string LayoutNavigationHouses {
            get {
                return ResourceManager.GetString("LayoutNavigationHouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ділянки.
        /// </summary>
        public static string LayoutNavigationLands {
            get {
                return ResourceManager.GetString("LayoutNavigationLands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статистика.
        /// </summary>
        public static string LayoutNavigationMain {
            get {
                return ResourceManager.GetString("LayoutNavigationMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувацька угода.
        /// </summary>
        public static string LicensePageTitle {
            get {
                return ResourceManager.GetString("LicensePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувацька угода.
        /// </summary>
        public static string LicenseTitle {
            get {
                return ResourceManager.GetString("LicenseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви завантажили максимальну кількість фотографій для оголошення. Якщо вам потрібно додати ще фотграфій &lt;a href=&quot;{0}&quot;&gt;оновіть ваш профайл&lt;/a&gt;.
        /// </summary>
        public static string LimitForPhotosIsReachedLabel {
            get {
                return ResourceManager.GetString("LimitForPhotosIsReachedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кількість відмічених оголошень.
        /// </summary>
        public static string ListNotesAnnouncementNumberLabel {
            get {
                return ResourceManager.GetString("ListNotesAnnouncementNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити.
        /// </summary>
        public static string ListNotesDeleteActionLabel {
            get {
                return ResourceManager.GetString("ListNotesDeleteActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва.
        /// </summary>
        public static string ListNotesNameLabel {
            get {
                return ResourceManager.GetString("ListNotesNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список нотатків.
        /// </summary>
        public static string ListNotesTitle {
            get {
                return ResourceManager.GetString("ListNotesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перегляд.
        /// </summary>
        public static string ListNotesViewActionLabel {
            get {
                return ResourceManager.GetString("ListNotesViewActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увійти.
        /// </summary>
        public static string LoginMessage {
            get {
                return ResourceManager.GetString("LoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невірні логін або/і пароль..
        /// </summary>
        public static string LoginPageLoginError {
            get {
                return ResourceManager.GetString("LoginPageLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string LoginPagePassword {
            get {
                return ResourceManager.GetString("LoginPagePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увійти.
        /// </summary>
        public static string LoginPageSignInButton {
            get {
                return ResourceManager.GetString("LoginPageSignInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вхід.
        /// </summary>
        public static string LoginPageTitle {
            get {
                return ResourceManager.GetString("LoginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правдивість даного користувача не підтверджена. Перейдіть за послинням, яке відправлене на електронну пошту даного користувача. .
        /// </summary>
        public static string LoginPageUserIsntConfirmedError {
            get {
                return ResourceManager.GetString("LoginPageUserIsntConfirmedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер телефону.
        /// </summary>
        public static string LoginPageUserPhone {
            get {
                return ResourceManager.GetString("LoginPageUserPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вийти.
        /// </summary>
        public static string LogoutMessage {
            get {
                return ResourceManager.GetString("LogoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нові квартири.
        /// </summary>
        public static string MailServiceMailSubject {
            get {
                return ResourceManager.GetString("MailServiceMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зміна ціни за м. кв. в {0} р-н.
        /// </summary>
        public static string MainIndexTitleDistrictHistoryChart {
            get {
                return ResourceManager.GetString("MainIndexTitleDistrictHistoryChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Середня ціна за м. кв. в різних районах Львова.
        /// </summary>
        public static string MainIndexTitleDistrictsChart {
            get {
                return ResourceManager.GetString("MainIndexTitleDistrictsChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сайт нерухомості.
        /// </summary>
        public static string MainTitleAddition {
            get {
                return ResourceManager.GetString("MainTitleAddition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не можливо додати більше {0} додаткових номерів!.
        /// </summary>
        public static string MaxNumbersLimitReached {
            get {
                return ResourceManager.GetString("MaxNumbersLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номери телефонів.
        /// </summary>
        public static string MobileNumbersProfileManagerTitle {
            get {
                return ResourceManager.GetString("MobileNumbersProfileManagerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вибачте, за даним запитом поки що немає оголошень.
        /// </summary>
        public static string NoSearchResults {
            get {
                return ResourceManager.GetString("NoSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відзначити.
        /// </summary>
        public static string NoteAddLabel {
            get {
                return ResourceManager.GetString("NoteAddLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити все.
        /// </summary>
        public static string NoteClearActionLabel {
            get {
                return ResourceManager.GetString("NoteClearActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нотатка за {0}.
        /// </summary>
        public static string NoteNamePattern {
            get {
                return ResourceManager.GetString("NoteNamePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скасувати.
        /// </summary>
        public static string NoteRemoveLabel {
            get {
                return ResourceManager.GetString("NoteRemoveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відзначені оголошення.
        /// </summary>
        public static string NotesIndexTitle {
            get {
                return ResourceManager.GetString("NotesIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невідомо.
        /// </summary>
        public static string NullableBoolTextHasNoValueLabel {
            get {
                return ResourceManager.GetString("NullableBoolTextHasNoValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to або.
        /// </summary>
        public static string OrLabel {
            get {
                return ResourceManager.GetString("OrLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Змінити пароль.
        /// </summary>
        public static string PasswordProfileManagerTitle {
            get {
                return ResourceManager.GetString("PasswordProfileManagerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви можете завантажити {0} фотографій.
        /// </summary>
        public static string PhotosLeft {
            get {
                return ResourceManager.GetString("PhotosLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Немає.
        /// </summary>
        public static string PresentTypeValueAbsentLabel {
            get {
                return ResourceManager.GetString("PresentTypeValueAbsentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Є.
        /// </summary>
        public static string PresentTypeValuePresentLabel {
            get {
                return ResourceManager.GetString("PresentTypeValuePresentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви досягли максимально можливу кількість оголошень. .
        /// </summary>
        public static string ProfileAnnouncementsLimitMessage {
            get {
                return ResourceManager.GetString("ProfileAnnouncementsLimitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Купити.
        /// </summary>
        public static string ProfileApplyButtonLabel {
            get {
                return ResourceManager.GetString("ProfileApplyButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продовжити.
        /// </summary>
        public static string ProfileContinueButtonLabel {
            get {
                return ResourceManager.GetString("ProfileContinueButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальна к-сть оголошень.
        /// </summary>
        public static string ProfileMaxAnnouncementsLabel {
            get {
                return ResourceManager.GetString("ProfileMaxAnnouncementsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальна к-сть фотографій для оголошення.
        /// </summary>
        public static string ProfileMaxPhotosPerAnnouncementsLabel {
            get {
                return ResourceManager.GetString("ProfileMaxPhotosPerAnnouncementsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поточний пароль не вірний.
        /// </summary>
        public static string ProfileOldPasswordIsNotCorrectMessage {
            get {
                return ResourceManager.GetString("ProfileOldPasswordIsNotCorrectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ціна за місяць.
        /// </summary>
        public static string ProfilePriceLabel {
            get {
                return ResourceManager.GetString("ProfilePriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш тарифний план занчується.
        /// </summary>
        public static string ProfilesExpireLabel {
            get {
                return ResourceManager.GetString("ProfilesExpireLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ніколи.
        /// </summary>
        public static string ProfilesExpireNeverLabel {
            get {
                return ResourceManager.GetString("ProfilesExpireNeverLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список тарифних планів.
        /// </summary>
        public static string ProfilesListLabel {
            get {
                return ResourceManager.GetString("ProfilesListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зареєструватися.
        /// </summary>
        public static string RegisterLabel {
            get {
                return ResourceManager.GetString("RegisterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Погано введена електронна пошта.
        /// </summary>
        public static string RegisterPageBadEmailError {
            get {
                return ResourceManager.GetString("RegisterPageBadEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отримувати електронні листи про нові оголошення на сайті.
        /// </summary>
        public static string RegisterPageCanReceiveMails {
            get {
                return ResourceManager.GetString("RegisterPageCanReceiveMails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролі не співпадають.
        /// </summary>
        public static string RegisterPageComparePasswordsError {
            get {
                return ResourceManager.GetString("RegisterPageComparePasswordsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підтвердіти пароль.
        /// </summary>
        public static string RegisterPageConfirmPassword {
            get {
                return ResourceManager.GetString("RegisterPageConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть адресу електронної пошти, до якої Ви маєте доступ. Після реєстрації, на введену Вами адресу, буде вислано електроне повідомлення. Вам потрібно буде перейти за посилання, яке буде у цьому листі, для подальшого подання оголошень..
        /// </summary>
        public static string RegisterPageEmailHintMessage {
            get {
                return ResourceManager.GetString("RegisterPageEmailHintMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Електронна пошта.
        /// </summary>
        public static string RegisterPageEmailLabel {
            get {
                return ResourceManager.GetString("RegisterPageEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не правильно заповнені дані.
        /// </summary>
        public static string RegisterPageError {
            get {
                return ResourceManager.GetString("RegisterPageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повернутися.
        /// </summary>
        public static string RegisterPageGoBack {
            get {
                return ResourceManager.GetString("RegisterPageGoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я погоджуюся з усіма положеннями щодо використання сайту, які описані на цій &lt;a href=&quot;{0}&quot;&gt;сторінці&lt;/a&gt;..
        /// </summary>
        public static string RegisterPageIAgreeWithUserTerms {
            get {
                return ResourceManager.GetString("RegisterPageIAgreeWithUserTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string RegisterPagePassword {
            get {
                return ResourceManager.GetString("RegisterPagePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль містити мінімум {0} символів.
        /// </summary>
        public static string RegisterPagePasswordTooShortError {
            get {
                return ResourceManager.GetString("RegisterPagePasswordTooShortError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувач з даним номером телефону вже зареєстрований. Вкажіть інший номер телефону..
        /// </summary>
        public static string RegisterPagePhoneNumberIsUsedAlready {
            get {
                return ResourceManager.GetString("RegisterPagePhoneNumberIsUsedAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зареєструватися.
        /// </summary>
        public static string RegisterPageRegisterButton {
            get {
                return ResourceManager.GetString("RegisterPageRegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невірний номер телефону..
        /// </summary>
        public static string RegisterPageShortPhoneNumber {
            get {
                return ResourceManager.GetString("RegisterPageShortPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви були успішно зареєстровані. На вашу електронну пошту вислано повідомлення для підтвердження правдивості користувача. Перейдіть за посилання у цьому повідомленню і тоді Ви зможете подавати оголошення..
        /// </summary>
        public static string RegisterPageSuccessMessage {
            get {
                return ResourceManager.GetString("RegisterPageSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер телефону.
        /// </summary>
        public static string RegisterPageTelephoneNumberLabel {
            get {
                return ResourceManager.GetString("RegisterPageTelephoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реєстрація.
        /// </summary>
        public static string RegisterPageTitle {
            get {
                return ResourceManager.GetString("RegisterPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я.
        /// </summary>
        public static string RegisterPageUserNameLabel {
            get {
                return ResourceManager.GetString("RegisterPageUserNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;Увага акція!&lt;/h4&gt;Подайте оголошення до {0} і ви отримаєте можливість подати до {1} оголошень до {2}..
        /// </summary>
        public static string RegisterShareMessage {
            get {
                return ResourceManager.GetString("RegisterShareMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оренда довгострокова.
        /// </summary>
        public static string RentLabel {
            get {
                return ResourceManager.GetString("RentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Оренда короткострокова.
        /// </summary>
        public static string RentShortLabel {
            get {
                return ResourceManager.GetString("RentShortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле {0} є обов&apos;язковим для введення.
        /// </summary>
        public static string RequiredMessage {
            get {
                return ResourceManager.GetString("RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відправити ще раз повідомлення з кодом підтвердження.
        /// </summary>
        public static string ResendEmailAgainLabel {
            get {
                return ResourceManager.GetString("ResendEmailAgainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відіслати повідомлення.
        /// </summary>
        public static string SendConfirmEmailSendButton {
            get {
                return ResourceManager.GetString("SendConfirmEmailSendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повідомлення з підтвердженням успішно відправленне.
        /// </summary>
        public static string SendConfirmEmailSuccess {
            get {
                return ResourceManager.GetString("SendConfirmEmailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відсилання листа з підтвердженням.
        /// </summary>
        public static string SendConfirmEmailTitle {
            get {
                return ResourceManager.GetString("SendConfirmEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви зареєструвані на сайті {0}. &lt;p&gt;Ваш новий пароль:{1}&lt;/p&gt;&lt;p&gt;Новий пароль дійсний до {2}. Якщо Ви не авторизуєтесь до {2} з новим паролем на сайті {0}, тоді він буде замінений на старий пароль.&lt;/p&gt; &lt;p&gt;Якщо Ви не реєструвалися на {0}, то проігноруйте цей лист.&lt;/p&gt;.
        /// </summary>
        public static string SendPasswordMailBody {
            get {
                return ResourceManager.GetString("SendPasswordMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відновлення паролю - сайт нерухомості.
        /// </summary>
        public static string SendPasswordMailTitle {
            get {
                return ResourceManager.GetString("SendPasswordMailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зробити відгук видимий для всіх.
        /// </summary>
        public static string ShowFeedbackForAllLabel {
            get {
                return ResourceManager.GetString("ShowFeedbackForAllLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ар.
        /// </summary>
        public static string SquareUnitAreLabel {
            get {
                return ResourceManager.GetString("SquareUnitAreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to га.
        /// </summary>
        public static string SquareUnitHectareLabel {
            get {
                return ResourceManager.GetString("SquareUnitHectareLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to м2.
        /// </summary>
        public static string SquareUnitSquareMetersLabel {
            get {
                return ResourceManager.GetString("SquareUnitSquareMetersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статистика.
        /// </summary>
        public static string StatisticPageTitle {
            get {
                return ResourceManager.GetString("StatisticPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Весь час.
        /// </summary>
        public static string TimePeriodAllTime {
            get {
                return ResourceManager.GetString("TimePeriodAllTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Два останніх місяці.
        /// </summary>
        public static string TimePeriodLast2Months {
            get {
                return ResourceManager.GetString("TimePeriodLast2Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Останній місяць.
        /// </summary>
        public static string TimePeriodLastMonth {
            get {
                return ResourceManager.GetString("TimePeriodLastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не важливо.
        /// </summary>
        public static string UnimportantLabel {
            get {
                return ResourceManager.GetString("UnimportantLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невідомо.
        /// </summary>
        public static string UnknownLabel {
            get {
                return ResourceManager.GetString("UnknownLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гроші не надіслано. Сталася помилка під час оновлення тарифного плану. Якщо у вас виникли запитання звертайтесь за номером телефону {0}..
        /// </summary>
        public static string UpdateFail {
            get {
                return ResourceManager.GetString("UpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша заявка на збільшення ліміту оголошень прийнята. Після отримання відповіді від банку на Вашу електронну пошту буде вислано лист з підвердженням. .
        /// </summary>
        public static string UpdateLimitWaitingLabel {
            get {
                return ResourceManager.GetString("UpdateLimitWaitingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оновлення тарифного плану до .
        /// </summary>
        public static string UpdateProfileToLable {
            get {
                return ResourceManager.GetString("UpdateProfileToLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш тарифний план оновлено. Ви можете додавати нові оголошення. Дякуємо..
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дані успішно збережено.
        /// </summary>
        public static string UserDataSavedMessage {
            get {
                return ResourceManager.GetString("UserDataSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такого користувача не існує.
        /// </summary>
        public static string UserIsNotFoundMessage {
            get {
                return ResourceManager.GetString("UserIsNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підтвердіть новий пароль.
        /// </summary>
        public static string UserProfileConfirmNewPasswordLabel {
            get {
                return ResourceManager.GetString("UserProfileConfirmNewPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новий пароль.
        /// </summary>
        public static string UserProfileNewPasswordLabel {
            get {
                return ResourceManager.GetString("UserProfileNewPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поточний пароль.
        /// </summary>
        public static string UserProfileOldPasswordLabel {
            get {
                return ResourceManager.GetString("UserProfileOldPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цегла.
        /// </summary>
        public static string WallMaterialCeglaLabel {
            get {
                return ResourceManager.GetString("WallMaterialCeglaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Газбетон.
        /// </summary>
        public static string WallMaterialGasBetonLabel {
            get {
                return ResourceManager.GetString("WallMaterialGasBetonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Панель.
        /// </summary>
        public static string WallMaterialPanelLabel {
            get {
                return ResourceManager.GetString("WallMaterialPanelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невідомо.
        /// </summary>
        public static string WallMaterialUnknownLabel {
            get {
                return ResourceManager.GetString("WallMaterialUnknownLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Електронна пошта.
        /// </summary>
        public static string WebsiteEmailAddress {
            get {
                return ResourceManager.GetString("WebsiteEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контактний телефон.
        /// </summary>
        public static string WebsiteMobileNumber {
            get {
                return ResourceManager.GetString("WebsiteMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оголошення з нерухомості.
        /// </summary>
        public static string WebsiteTitle {
            get {
                return ResourceManager.GetString("WebsiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;Вас вітає новий сайт для розміщення оголошень про оренду і продаж нерухомості. &lt;/h4&gt;.
        /// </summary>
        public static string WelcomeMassage {
            get {
                return ResourceManager.GetString("WelcomeMassage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва вашого тарифного плану.
        /// </summary>
        public static string YourProfileLabel {
            get {
                return ResourceManager.GetString("YourProfileLabel", resourceCulture);
            }
        }
    }
}
